//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OffTheGrit1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/GroupProject")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OffTheGrit1.ServiceReference1.Order[] OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime User_Acc_Creation_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool User_ActivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_Card_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_Card_NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_Password_HashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_Phone_NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_Security_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char User_TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_Valid_ThruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool User_isOnlineField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OffTheGrit1.ServiceReference1.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime User_Acc_Creation_Date {
            get {
                return this.User_Acc_Creation_DateField;
            }
            set {
                if ((this.User_Acc_Creation_DateField.Equals(value) != true)) {
                    this.User_Acc_Creation_DateField = value;
                    this.RaisePropertyChanged("User_Acc_Creation_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool User_Activity {
            get {
                return this.User_ActivityField;
            }
            set {
                if ((this.User_ActivityField.Equals(value) != true)) {
                    this.User_ActivityField = value;
                    this.RaisePropertyChanged("User_Activity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Address {
            get {
                return this.User_AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.User_AddressField, value) != true)) {
                    this.User_AddressField = value;
                    this.RaisePropertyChanged("User_Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Card_Name {
            get {
                return this.User_Card_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_Card_NameField, value) != true)) {
                    this.User_Card_NameField = value;
                    this.RaisePropertyChanged("User_Card_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Card_No {
            get {
                return this.User_Card_NoField;
            }
            set {
                if ((object.ReferenceEquals(this.User_Card_NoField, value) != true)) {
                    this.User_Card_NoField = value;
                    this.RaisePropertyChanged("User_Card_No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Email {
            get {
                return this.User_EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.User_EmailField, value) != true)) {
                    this.User_EmailField = value;
                    this.RaisePropertyChanged("User_Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_ID {
            get {
                return this.User_IDField;
            }
            set {
                if ((this.User_IDField.Equals(value) != true)) {
                    this.User_IDField = value;
                    this.RaisePropertyChanged("User_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Name {
            get {
                return this.User_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_NameField, value) != true)) {
                    this.User_NameField = value;
                    this.RaisePropertyChanged("User_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Password_Hash {
            get {
                return this.User_Password_HashField;
            }
            set {
                if ((object.ReferenceEquals(this.User_Password_HashField, value) != true)) {
                    this.User_Password_HashField = value;
                    this.RaisePropertyChanged("User_Password_Hash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Phone_Number {
            get {
                return this.User_Phone_NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.User_Phone_NumberField, value) != true)) {
                    this.User_Phone_NumberField = value;
                    this.RaisePropertyChanged("User_Phone_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Security_Code {
            get {
                return this.User_Security_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.User_Security_CodeField, value) != true)) {
                    this.User_Security_CodeField = value;
                    this.RaisePropertyChanged("User_Security_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Surname {
            get {
                return this.User_SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_SurnameField, value) != true)) {
                    this.User_SurnameField = value;
                    this.RaisePropertyChanged("User_Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char User_Type {
            get {
                return this.User_TypeField;
            }
            set {
                if ((this.User_TypeField.Equals(value) != true)) {
                    this.User_TypeField = value;
                    this.RaisePropertyChanged("User_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Valid_Thru {
            get {
                return this.User_Valid_ThruField;
            }
            set {
                if ((object.ReferenceEquals(this.User_Valid_ThruField, value) != true)) {
                    this.User_Valid_ThruField = value;
                    this.RaisePropertyChanged("User_Valid_Thru");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool User_isOnline {
            get {
                return this.User_isOnlineField;
            }
            set {
                if ((this.User_isOnlineField.Equals(value) != true)) {
                    this.User_isOnlineField = value;
                    this.RaisePropertyChanged("User_isOnline");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/GroupProject")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Customer_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OffTheGrit1.ServiceReference1.Invoice InvoiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Invoice_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Order_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Order_Delivery_StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Order_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OffTheGrit1.ServiceReference1.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Customer_ID {
            get {
                return this.Customer_IDField;
            }
            set {
                if ((this.Customer_IDField.Equals(value) != true)) {
                    this.Customer_IDField = value;
                    this.RaisePropertyChanged("Customer_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OffTheGrit1.ServiceReference1.Invoice Invoice {
            get {
                return this.InvoiceField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceField, value) != true)) {
                    this.InvoiceField = value;
                    this.RaisePropertyChanged("Invoice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Invoice_ID {
            get {
                return this.Invoice_IDField;
            }
            set {
                if ((this.Invoice_IDField.Equals(value) != true)) {
                    this.Invoice_IDField = value;
                    this.RaisePropertyChanged("Invoice_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Order_Date {
            get {
                return this.Order_DateField;
            }
            set {
                if ((this.Order_DateField.Equals(value) != true)) {
                    this.Order_DateField = value;
                    this.RaisePropertyChanged("Order_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Order_Delivery_Status {
            get {
                return this.Order_Delivery_StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.Order_Delivery_StatusField, value) != true)) {
                    this.Order_Delivery_StatusField = value;
                    this.RaisePropertyChanged("Order_Delivery_Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order_ID {
            get {
                return this.Order_IDField;
            }
            set {
                if ((this.Order_IDField.Equals(value) != true)) {
                    this.Order_IDField = value;
                    this.RaisePropertyChanged("Order_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OffTheGrit1.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoice", Namespace="http://schemas.datacontract.org/2004/07/GroupProject")]
    [System.SerializableAttribute()]
    public partial class Invoice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Customer_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Invoice_Created_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Invoice_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OffTheGrit1.ServiceReference1.Invoiceline[] InvoicelinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OffTheGrit1.ServiceReference1.Order[] OrdersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Customer_ID {
            get {
                return this.Customer_IDField;
            }
            set {
                if ((this.Customer_IDField.Equals(value) != true)) {
                    this.Customer_IDField = value;
                    this.RaisePropertyChanged("Customer_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Invoice_Created_Date {
            get {
                return this.Invoice_Created_DateField;
            }
            set {
                if ((this.Invoice_Created_DateField.Equals(value) != true)) {
                    this.Invoice_Created_DateField = value;
                    this.RaisePropertyChanged("Invoice_Created_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Invoice_ID {
            get {
                return this.Invoice_IDField;
            }
            set {
                if ((this.Invoice_IDField.Equals(value) != true)) {
                    this.Invoice_IDField = value;
                    this.RaisePropertyChanged("Invoice_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OffTheGrit1.ServiceReference1.Invoiceline[] Invoicelines {
            get {
                return this.InvoicelinesField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoicelinesField, value) != true)) {
                    this.InvoicelinesField = value;
                    this.RaisePropertyChanged("Invoicelines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OffTheGrit1.ServiceReference1.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoiceline", Namespace="http://schemas.datacontract.org/2004/07/GroupProject")]
    [System.SerializableAttribute()]
    public partial class Invoiceline : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OffTheGrit1.ServiceReference1.Invoice InvoiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Invoice_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Invoiceline_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Invoiceline_QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OffTheGrit1.ServiceReference1.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Product_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OffTheGrit1.ServiceReference1.Invoice Invoice {
            get {
                return this.InvoiceField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceField, value) != true)) {
                    this.InvoiceField = value;
                    this.RaisePropertyChanged("Invoice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Invoice_ID {
            get {
                return this.Invoice_IDField;
            }
            set {
                if ((this.Invoice_IDField.Equals(value) != true)) {
                    this.Invoice_IDField = value;
                    this.RaisePropertyChanged("Invoice_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Invoiceline_ID {
            get {
                return this.Invoiceline_IDField;
            }
            set {
                if ((this.Invoiceline_IDField.Equals(value) != true)) {
                    this.Invoiceline_IDField = value;
                    this.RaisePropertyChanged("Invoiceline_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Invoiceline_Quantity {
            get {
                return this.Invoiceline_QuantityField;
            }
            set {
                if ((this.Invoiceline_QuantityField.Equals(value) != true)) {
                    this.Invoiceline_QuantityField = value;
                    this.RaisePropertyChanged("Invoiceline_Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OffTheGrit1.ServiceReference1.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Product_ID {
            get {
                return this.Product_IDField;
            }
            set {
                if ((this.Product_IDField.Equals(value) != true)) {
                    this.Product_IDField = value;
                    this.RaisePropertyChanged("Product_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/GroupProject")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OffTheGrit1.ServiceReference1.Category CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Category_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OffTheGrit1.ServiceReference1.Invoiceline[] InvoicelinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Product_AvailabilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Product_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Product_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Product_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Product_QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Product_Updated_AtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OffTheGrit1.ServiceReference1.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Category_ID {
            get {
                return this.Category_IDField;
            }
            set {
                if ((this.Category_IDField.Equals(value) != true)) {
                    this.Category_IDField = value;
                    this.RaisePropertyChanged("Category_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OffTheGrit1.ServiceReference1.Invoiceline[] Invoicelines {
            get {
                return this.InvoicelinesField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoicelinesField, value) != true)) {
                    this.InvoicelinesField = value;
                    this.RaisePropertyChanged("Invoicelines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Product_Availability {
            get {
                return this.Product_AvailabilityField;
            }
            set {
                if ((this.Product_AvailabilityField.Equals(value) != true)) {
                    this.Product_AvailabilityField = value;
                    this.RaisePropertyChanged("Product_Availability");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_Description {
            get {
                return this.Product_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_DescriptionField, value) != true)) {
                    this.Product_DescriptionField = value;
                    this.RaisePropertyChanged("Product_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Product_ID {
            get {
                return this.Product_IDField;
            }
            set {
                if ((this.Product_IDField.Equals(value) != true)) {
                    this.Product_IDField = value;
                    this.RaisePropertyChanged("Product_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_Image {
            get {
                return this.Product_ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_ImageField, value) != true)) {
                    this.Product_ImageField = value;
                    this.RaisePropertyChanged("Product_Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product_Name {
            get {
                return this.Product_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Product_NameField, value) != true)) {
                    this.Product_NameField = value;
                    this.RaisePropertyChanged("Product_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Product_Price {
            get {
                return this.Product_PriceField;
            }
            set {
                if ((this.Product_PriceField.Equals(value) != true)) {
                    this.Product_PriceField = value;
                    this.RaisePropertyChanged("Product_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Product_Quantity {
            get {
                return this.Product_QuantityField;
            }
            set {
                if ((this.Product_QuantityField.Equals(value) != true)) {
                    this.Product_QuantityField = value;
                    this.RaisePropertyChanged("Product_Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Product_Updated_At {
            get {
                return this.Product_Updated_AtField;
            }
            set {
                if ((this.Product_Updated_AtField.Equals(value) != true)) {
                    this.Product_Updated_AtField = value;
                    this.RaisePropertyChanged("Product_Updated_At");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/GroupProject")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Category_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Category_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OffTheGrit1.ServiceReference1.Product[] ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Category_ID {
            get {
                return this.Category_IDField;
            }
            set {
                if ((this.Category_IDField.Equals(value) != true)) {
                    this.Category_IDField = value;
                    this.RaisePropertyChanged("Category_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category_Name {
            get {
                return this.Category_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Category_NameField, value) != true)) {
                    this.Category_NameField = value;
                    this.RaisePropertyChanged("Category_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OffTheGrit1.ServiceReference1.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService2")]
    public interface IService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Register", ReplyAction="http://tempuri.org/IService2/RegisterResponse")]
        int Register(string name, string surname, string phone_number, string email, string password, string confirm, char type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Register", ReplyAction="http://tempuri.org/IService2/RegisterResponse")]
        System.Threading.Tasks.Task<int> RegisterAsync(string name, string surname, string phone_number, string email, string password, string confirm, char type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/login", ReplyAction="http://tempuri.org/IService2/loginResponse")]
        OffTheGrit1.ServiceReference1.User login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/login", ReplyAction="http://tempuri.org/IService2/loginResponse")]
        System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.User> loginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/editUser", ReplyAction="http://tempuri.org/IService2/editUserResponse")]
        bool editUser(int id, string address, string cardholdername, string cardno, string cvv, string expdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/editUser", ReplyAction="http://tempuri.org/IService2/editUserResponse")]
        System.Threading.Tasks.Task<bool> editUserAsync(int id, string address, string cardholdername, string cardno, string cvv, string expdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getUser", ReplyAction="http://tempuri.org/IService2/getUserResponse")]
        OffTheGrit1.ServiceReference1.User getUser(int user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getUser", ReplyAction="http://tempuri.org/IService2/getUserResponse")]
        System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.User> getUserAsync(int user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getUsers", ReplyAction="http://tempuri.org/IService2/getUsersResponse")]
        OffTheGrit1.ServiceReference1.User[] getUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getUsers", ReplyAction="http://tempuri.org/IService2/getUsersResponse")]
        System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.User[]> getUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getProduct", ReplyAction="http://tempuri.org/IService2/getProductResponse")]
        OffTheGrit1.ServiceReference1.Product getProduct(int prod_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getProduct", ReplyAction="http://tempuri.org/IService2/getProductResponse")]
        System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Product> getProductAsync(int prod_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getAllProducts", ReplyAction="http://tempuri.org/IService2/getAllProductsResponse")]
        OffTheGrit1.ServiceReference1.Product[] getAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getAllProducts", ReplyAction="http://tempuri.org/IService2/getAllProductsResponse")]
        System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Product[]> getAllProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getActiveProducts", ReplyAction="http://tempuri.org/IService2/getActiveProductsResponse")]
        OffTheGrit1.ServiceReference1.Product[] getActiveProducts(int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getActiveProducts", ReplyAction="http://tempuri.org/IService2/getActiveProductsResponse")]
        System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Product[]> getActiveProductsAsync(int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/isProdAdded", ReplyAction="http://tempuri.org/IService2/isProdAddedResponse")]
        bool isProdAdded(int category_ID, string product_name, string product_image, decimal product_price, string product_description, int product_quantity, bool product_availability, System.DateTime product_UpdatedAt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/isProdAdded", ReplyAction="http://tempuri.org/IService2/isProdAddedResponse")]
        System.Threading.Tasks.Task<bool> isProdAddedAsync(int category_ID, string product_name, string product_image, decimal product_price, string product_description, int product_quantity, bool product_availability, System.DateTime product_UpdatedAt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/editProduct", ReplyAction="http://tempuri.org/IService2/editProductResponse")]
        bool editProduct(OffTheGrit1.ServiceReference1.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/editProduct", ReplyAction="http://tempuri.org/IService2/editProductResponse")]
        System.Threading.Tasks.Task<bool> editProductAsync(OffTheGrit1.ServiceReference1.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getCategory", ReplyAction="http://tempuri.org/IService2/getCategoryResponse")]
        OffTheGrit1.ServiceReference1.Category getCategory(int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getCategory", ReplyAction="http://tempuri.org/IService2/getCategoryResponse")]
        System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Category> getCategoryAsync(int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/deleteProduct", ReplyAction="http://tempuri.org/IService2/deleteProductResponse")]
        bool deleteProduct(int prod_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/deleteProduct", ReplyAction="http://tempuri.org/IService2/deleteProductResponse")]
        System.Threading.Tasks.Task<bool> deleteProductAsync(int prod_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/addInvoice", ReplyAction="http://tempuri.org/IService2/addInvoiceResponse")]
        bool addInvoice(int customer_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/addInvoice", ReplyAction="http://tempuri.org/IService2/addInvoiceResponse")]
        System.Threading.Tasks.Task<bool> addInvoiceAsync(int customer_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getInvoice", ReplyAction="http://tempuri.org/IService2/getInvoiceResponse")]
        OffTheGrit1.ServiceReference1.Invoice getInvoice(int invoice_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getInvoice", ReplyAction="http://tempuri.org/IService2/getInvoiceResponse")]
        System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Invoice> getInvoiceAsync(int invoice_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getInvoices", ReplyAction="http://tempuri.org/IService2/getInvoicesResponse")]
        OffTheGrit1.ServiceReference1.Invoice[] getInvoices(int Customer_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getInvoices", ReplyAction="http://tempuri.org/IService2/getInvoicesResponse")]
        System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Invoice[]> getInvoicesAsync(int Customer_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/addInvoiceLine", ReplyAction="http://tempuri.org/IService2/addInvoiceLineResponse")]
        bool addInvoiceLine(int invoice_id, int product_id, int invoiceline_quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/addInvoiceLine", ReplyAction="http://tempuri.org/IService2/addInvoiceLineResponse")]
        System.Threading.Tasks.Task<bool> addInvoiceLineAsync(int invoice_id, int product_id, int invoiceline_quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getIvoiceLineItems", ReplyAction="http://tempuri.org/IService2/getIvoiceLineItemsResponse")]
        OffTheGrit1.ServiceReference1.Invoiceline[] getIvoiceLineItems(int inv_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getIvoiceLineItems", ReplyAction="http://tempuri.org/IService2/getIvoiceLineItemsResponse")]
        System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Invoiceline[]> getIvoiceLineItemsAsync(int inv_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/addOrder", ReplyAction="http://tempuri.org/IService2/addOrderResponse")]
        bool addOrder(int customer_id, string order_Delivery_Staus, int invoice_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/addOrder", ReplyAction="http://tempuri.org/IService2/addOrderResponse")]
        System.Threading.Tasks.Task<bool> addOrderAsync(int customer_id, string order_Delivery_Staus, int invoice_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getOrder", ReplyAction="http://tempuri.org/IService2/getOrderResponse")]
        OffTheGrit1.ServiceReference1.Order getOrder(int order_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getOrder", ReplyAction="http://tempuri.org/IService2/getOrderResponse")]
        System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Order> getOrderAsync(int order_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getOrders", ReplyAction="http://tempuri.org/IService2/getOrdersResponse")]
        OffTheGrit1.ServiceReference1.Order[] getOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getOrders", ReplyAction="http://tempuri.org/IService2/getOrdersResponse")]
        System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Order[]> getOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/editOrderStatus", ReplyAction="http://tempuri.org/IService2/editOrderStatusResponse")]
        bool editOrderStatus(int orderID, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/editOrderStatus", ReplyAction="http://tempuri.org/IService2/editOrderStatusResponse")]
        System.Threading.Tasks.Task<bool> editOrderStatusAsync(int orderID, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getProductsByQuery", ReplyAction="http://tempuri.org/IService2/getProductsByQueryResponse")]
        OffTheGrit1.ServiceReference1.Product[] getProductsByQuery(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getProductsByQuery", ReplyAction="http://tempuri.org/IService2/getProductsByQueryResponse")]
        System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Product[]> getProductsByQueryAsync(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getAllInvoices", ReplyAction="http://tempuri.org/IService2/getAllInvoicesResponse")]
        OffTheGrit1.ServiceReference1.Invoice[] getAllInvoices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getAllInvoices", ReplyAction="http://tempuri.org/IService2/getAllInvoicesResponse")]
        System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Invoice[]> getAllInvoicesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getInvoiceLineItems", ReplyAction="http://tempuri.org/IService2/getInvoiceLineItemsResponse")]
        OffTheGrit1.ServiceReference1.Invoiceline[] getInvoiceLineItems(int invoiceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getInvoiceLineItems", ReplyAction="http://tempuri.org/IService2/getInvoiceLineItemsResponse")]
        System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Invoiceline[]> getInvoiceLineItemsAsync(int invoiceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getAllInvoiceLineItems", ReplyAction="http://tempuri.org/IService2/getAllInvoiceLineItemsResponse")]
        OffTheGrit1.ServiceReference1.Invoiceline[] getAllInvoiceLineItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/getAllInvoiceLineItems", ReplyAction="http://tempuri.org/IService2/getAllInvoiceLineItemsResponse")]
        System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Invoiceline[]> getAllInvoiceLineItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/addCard", ReplyAction="http://tempuri.org/IService2/addCardResponse")]
        bool addCard(string card_acc, int Customer_ID, string card_number, string card_cvv, System.DateTime exp_date, int card_isActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/addCard", ReplyAction="http://tempuri.org/IService2/addCardResponse")]
        System.Threading.Tasks.Task<bool> addCardAsync(string card_acc, int Customer_ID, string card_number, string card_cvv, System.DateTime exp_date, int card_isActive);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Channel : OffTheGrit1.ServiceReference1.IService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Client : System.ServiceModel.ClientBase<OffTheGrit1.ServiceReference1.IService2>, OffTheGrit1.ServiceReference1.IService2 {
        
        public Service2Client() {
        }
        
        public Service2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Register(string name, string surname, string phone_number, string email, string password, string confirm, char type) {
            return base.Channel.Register(name, surname, phone_number, email, password, confirm, type);
        }
        
        public System.Threading.Tasks.Task<int> RegisterAsync(string name, string surname, string phone_number, string email, string password, string confirm, char type) {
            return base.Channel.RegisterAsync(name, surname, phone_number, email, password, confirm, type);
        }
        
        public OffTheGrit1.ServiceReference1.User login(string email, string password) {
            return base.Channel.login(email, password);
        }
        
        public System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.User> loginAsync(string email, string password) {
            return base.Channel.loginAsync(email, password);
        }
        
        public bool editUser(int id, string address, string cardholdername, string cardno, string cvv, string expdate) {
            return base.Channel.editUser(id, address, cardholdername, cardno, cvv, expdate);
        }
        
        public System.Threading.Tasks.Task<bool> editUserAsync(int id, string address, string cardholdername, string cardno, string cvv, string expdate) {
            return base.Channel.editUserAsync(id, address, cardholdername, cardno, cvv, expdate);
        }
        
        public OffTheGrit1.ServiceReference1.User getUser(int user_id) {
            return base.Channel.getUser(user_id);
        }
        
        public System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.User> getUserAsync(int user_id) {
            return base.Channel.getUserAsync(user_id);
        }
        
        public OffTheGrit1.ServiceReference1.User[] getUsers() {
            return base.Channel.getUsers();
        }
        
        public System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.User[]> getUsersAsync() {
            return base.Channel.getUsersAsync();
        }
        
        public OffTheGrit1.ServiceReference1.Product getProduct(int prod_ID) {
            return base.Channel.getProduct(prod_ID);
        }
        
        public System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Product> getProductAsync(int prod_ID) {
            return base.Channel.getProductAsync(prod_ID);
        }
        
        public OffTheGrit1.ServiceReference1.Product[] getAllProducts() {
            return base.Channel.getAllProducts();
        }
        
        public System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Product[]> getAllProductsAsync() {
            return base.Channel.getAllProductsAsync();
        }
        
        public OffTheGrit1.ServiceReference1.Product[] getActiveProducts(int catID) {
            return base.Channel.getActiveProducts(catID);
        }
        
        public System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Product[]> getActiveProductsAsync(int catID) {
            return base.Channel.getActiveProductsAsync(catID);
        }
        
        public bool isProdAdded(int category_ID, string product_name, string product_image, decimal product_price, string product_description, int product_quantity, bool product_availability, System.DateTime product_UpdatedAt) {
            return base.Channel.isProdAdded(category_ID, product_name, product_image, product_price, product_description, product_quantity, product_availability, product_UpdatedAt);
        }
        
        public System.Threading.Tasks.Task<bool> isProdAddedAsync(int category_ID, string product_name, string product_image, decimal product_price, string product_description, int product_quantity, bool product_availability, System.DateTime product_UpdatedAt) {
            return base.Channel.isProdAddedAsync(category_ID, product_name, product_image, product_price, product_description, product_quantity, product_availability, product_UpdatedAt);
        }
        
        public bool editProduct(OffTheGrit1.ServiceReference1.Product product) {
            return base.Channel.editProduct(product);
        }
        
        public System.Threading.Tasks.Task<bool> editProductAsync(OffTheGrit1.ServiceReference1.Product product) {
            return base.Channel.editProductAsync(product);
        }
        
        public OffTheGrit1.ServiceReference1.Category getCategory(int catID) {
            return base.Channel.getCategory(catID);
        }
        
        public System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Category> getCategoryAsync(int catID) {
            return base.Channel.getCategoryAsync(catID);
        }
        
        public bool deleteProduct(int prod_id) {
            return base.Channel.deleteProduct(prod_id);
        }
        
        public System.Threading.Tasks.Task<bool> deleteProductAsync(int prod_id) {
            return base.Channel.deleteProductAsync(prod_id);
        }
        
        public bool addInvoice(int customer_ID) {
            return base.Channel.addInvoice(customer_ID);
        }
        
        public System.Threading.Tasks.Task<bool> addInvoiceAsync(int customer_ID) {
            return base.Channel.addInvoiceAsync(customer_ID);
        }
        
        public OffTheGrit1.ServiceReference1.Invoice getInvoice(int invoice_id) {
            return base.Channel.getInvoice(invoice_id);
        }
        
        public System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Invoice> getInvoiceAsync(int invoice_id) {
            return base.Channel.getInvoiceAsync(invoice_id);
        }
        
        public OffTheGrit1.ServiceReference1.Invoice[] getInvoices(int Customer_ID) {
            return base.Channel.getInvoices(Customer_ID);
        }
        
        public System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Invoice[]> getInvoicesAsync(int Customer_ID) {
            return base.Channel.getInvoicesAsync(Customer_ID);
        }
        
        public bool addInvoiceLine(int invoice_id, int product_id, int invoiceline_quantity) {
            return base.Channel.addInvoiceLine(invoice_id, product_id, invoiceline_quantity);
        }
        
        public System.Threading.Tasks.Task<bool> addInvoiceLineAsync(int invoice_id, int product_id, int invoiceline_quantity) {
            return base.Channel.addInvoiceLineAsync(invoice_id, product_id, invoiceline_quantity);
        }
        
        public OffTheGrit1.ServiceReference1.Invoiceline[] getIvoiceLineItems(int inv_id) {
            return base.Channel.getIvoiceLineItems(inv_id);
        }
        
        public System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Invoiceline[]> getIvoiceLineItemsAsync(int inv_id) {
            return base.Channel.getIvoiceLineItemsAsync(inv_id);
        }
        
        public bool addOrder(int customer_id, string order_Delivery_Staus, int invoice_id) {
            return base.Channel.addOrder(customer_id, order_Delivery_Staus, invoice_id);
        }
        
        public System.Threading.Tasks.Task<bool> addOrderAsync(int customer_id, string order_Delivery_Staus, int invoice_id) {
            return base.Channel.addOrderAsync(customer_id, order_Delivery_Staus, invoice_id);
        }
        
        public OffTheGrit1.ServiceReference1.Order getOrder(int order_id) {
            return base.Channel.getOrder(order_id);
        }
        
        public System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Order> getOrderAsync(int order_id) {
            return base.Channel.getOrderAsync(order_id);
        }
        
        public OffTheGrit1.ServiceReference1.Order[] getOrders() {
            return base.Channel.getOrders();
        }
        
        public System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Order[]> getOrdersAsync() {
            return base.Channel.getOrdersAsync();
        }
        
        public bool editOrderStatus(int orderID, string status) {
            return base.Channel.editOrderStatus(orderID, status);
        }
        
        public System.Threading.Tasks.Task<bool> editOrderStatusAsync(int orderID, string status) {
            return base.Channel.editOrderStatusAsync(orderID, status);
        }
        
        public OffTheGrit1.ServiceReference1.Product[] getProductsByQuery(string query) {
            return base.Channel.getProductsByQuery(query);
        }
        
        public System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Product[]> getProductsByQueryAsync(string query) {
            return base.Channel.getProductsByQueryAsync(query);
        }
        
        public OffTheGrit1.ServiceReference1.Invoice[] getAllInvoices() {
            return base.Channel.getAllInvoices();
        }
        
        public System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Invoice[]> getAllInvoicesAsync() {
            return base.Channel.getAllInvoicesAsync();
        }
        
        public OffTheGrit1.ServiceReference1.Invoiceline[] getInvoiceLineItems(int invoiceID) {
            return base.Channel.getInvoiceLineItems(invoiceID);
        }
        
        public System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Invoiceline[]> getInvoiceLineItemsAsync(int invoiceID) {
            return base.Channel.getInvoiceLineItemsAsync(invoiceID);
        }
        
        public OffTheGrit1.ServiceReference1.Invoiceline[] getAllInvoiceLineItems() {
            return base.Channel.getAllInvoiceLineItems();
        }
        
        public System.Threading.Tasks.Task<OffTheGrit1.ServiceReference1.Invoiceline[]> getAllInvoiceLineItemsAsync() {
            return base.Channel.getAllInvoiceLineItemsAsync();
        }
        
        public bool addCard(string card_acc, int Customer_ID, string card_number, string card_cvv, System.DateTime exp_date, int card_isActive) {
            return base.Channel.addCard(card_acc, Customer_ID, card_number, card_cvv, exp_date, card_isActive);
        }
        
        public System.Threading.Tasks.Task<bool> addCardAsync(string card_acc, int Customer_ID, string card_number, string card_cvv, System.DateTime exp_date, int card_isActive) {
            return base.Channel.addCardAsync(card_acc, Customer_ID, card_number, card_cvv, exp_date, card_isActive);
        }
    }
}
